ignore: {% set data = load_setup_py_data() %}
ignore: {% set version = data['version'] %}

package:
  name: orange3
  version: {{ data['version'] }}

source:
  git_url: ../

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main

  osx_is_app: True

  script:
    - python setup.py build -j1 bdist_wheel
    - if errorlevel 1 exit 1        # [win]
    - pip install --no-deps --no-cache --no-index -f dist Orange3=={{ version }}
    - if errorlevel 1 exit 1        # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy         1.14.*
    - cython
    - pip
    - wheel
    - sphinx
    - recommonmark
  run:
    - python
    - setuptools >=36.3
    - numpy >=1.16.0
    - scipy >=0.16.1
    - scikit-learn >=0.22.0,!=0.23.0
    - bottleneck >=1.0.0
    - chardet >=3.0.2
    - xlrd >=0.9.2
    - xlsxwriter
    - anyqt >=0.0.11
    - pyqt >=5.12,!=5.15.1
    - pyqtgraph >=0.11.0
    - joblib >=0.9.4
    - keyring
    - keyrings.alt
    - pip >=9.0
    - python.app  # [osx]
    - serverfiles
    - python-louvain >=0.13
    - requests
    - matplotlib-base >=2.0.0
    - openTSNE >=0.4.3
    - pandas >=1.0.0
    - pyyaml
    - orange-canvas-core >=0.1.18,<0.2a
    - orange-widget-base >=4.8.1
    - openpyxl
    - httpx >=0.12
    - baycomp >=1.0.2
    # cachecontrol (required by canvas core) <0.12.5 is incompatible with msgpack 1.0
    - cachecontrol >=0.12.6

test:
  # Python imports
  imports:
    - Orange
    - Orange.canvas.config

    - Orange.widgets
    - Orange.widgets.data
    - Orange.widgets.evaluate
    - Orange.widgets.model
    - Orange.widgets.unsupervised
    - Orange.widgets.visualize

    - Orange.classification
    - Orange.clustering
    - Orange.data
    - Orange.distance
    - Orange.evaluation
    - Orange.modelling
    - Orange.preprocess
    - Orange.projection
    - Orange.regression
    - Orange.statistics

  commands:
    - python -m unittest -v Orange.tests Orange.widgets.tests
    - orange-canvas --help

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: ../distribute/icon-48.png

about:
  home: http://orange.biolab.si/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Orange, a component-based data mining framework.'
