name: Lint workflow

on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        python: [3.7]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox
        run: pip install tox

      - name: Run Pylint
        run:  tox -e pylint-ci
